---
- name: Install and configure web server
  hosts: g1
  become: yes
  tasks:
    - name: Install httpd (Amazon/CentOS)
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'

    - name: Start and enable httpd (Amazon/CentOS)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'

    - name: Install apache2 (Ubuntu/Debian)
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Start and enable apache2 (Ubuntu/Debian)
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
...
